# Pytorch Fundamentals

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(f"PyTorch version: {torch.__version__}")

# Check PyTorch has access to MPS (Metal Performance Shader, Apple's GPU architecture)
print(f"Is MPS (Metal Performance Shader) built? {torch.backends.mps.is_built()}")
print(f"Is MPS available? {torch.backends.mps.is_available()}")

# Set the device
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {device}")

PyTorch version: 2.0.1
Is MPS (Metal Performance Shader) built? True
Is MPS available? True
Using device: mps


## Tensors
### Creating Tensors

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item() # get the tensor back as an int

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix = torch.tensor([[1,2],
                       [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [10]:
matrix.ndim

2

In [11]:
matrix[1]

tensor([3, 4])

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

In [17]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7427, 0.2713, 0.2575, 0.1413],
        [0.2917, 0.5503, 0.3776, 0.8994],
        [0.8793, 0.4877, 0.8534, 0.6798]])

In [18]:
random_tensor.ndim

2

In [19]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels i.e. RGB

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [20]:
zeros = torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Range of tensors and tensors-like

In [23]:
torch.arange(start=0, end=1000, step=50)

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [24]:
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [26]:
#float 32
float_32_tensor = torch.tensor([3.0, 2.0, 9.0],
                               dtype=None,
                               device=None, # what device is your tensor on? cuda, mps, cpu? 
                               requires_grad=False) # whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 2., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 2., 9.], dtype=torch.float16)

Errors when working with tensors are usually to do with the: 
* datatype
* shape
* device

In [29]:
random_tensor

tensor([[0.7427, 0.2713, 0.2575, 0.1413],
        [0.2917, 0.5503, 0.3776, 0.8994],
        [0.8793, 0.4877, 0.8534, 0.6798]])

In [30]:
print(f"Shape: {random_tensor.shape}")
print(f"Device: {random_tensor.device}")
print(f"Datatype: {random_tensor.dtype}")

Shape: torch.Size([3, 4])
Device: cpu
Datatype: torch.float32


### Tensor Operations

In [31]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [32]:
tensor + 10

tensor([11, 12, 13])

In [33]:
tensor - 10

tensor([-9, -8, -7])

In [34]:
tensor * 10

tensor([10, 20, 30])

In [35]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [36]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [37]:
torch.matmul(tensor, tensor)

tensor(14)

In [38]:
tensor = torch.tensor([[1,2,3,4,5],[1,3,4,5,5]])
tensor

tensor([[1, 2, 3, 4, 5],
        [1, 3, 4, 5, 5]])

In [39]:
tensor.T

tensor([[1, 1],
        [2, 3],
        [3, 4],
        [4, 5],
        [5, 5]])

In [40]:
tensor.shape, tensor.T.shape

(torch.Size([2, 5]), torch.Size([5, 2]))

### Tensor Aggregation

In [41]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
x.sum()

tensor(450)

In [43]:
x.min(), x.max()

(tensor(0), tensor(90))

In [44]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [45]:
x.argmax() # position of max

tensor(9)

In [46]:
x.argmin()

tensor(0)

### Reshaping, Stacking, Squeezing and Unsqueezing Tensors

**Reshaping** - reshape to a specific shape (has to have the same number of elements)

In [81]:
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [82]:
x.reshape(9, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [83]:
x.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

**View** - return a view of an input tensor of certain shape but share memory with the original tensor

In [84]:
z = x.view(1, 9) # like a deep copy
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [85]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [86]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

**Stacking** - combine multiple tensors i.e. vertically or horizontally stack them

In [87]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [88]:
x_stacked = torch.stack([x,x,x,x], dim=0) # dim = 0 vertically, 1 is horizontally typically you can have more dims depending on the dim of your tensor
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

**Squeezing** - Removes all the 1 dimensions of a tensor

In [89]:
x = torch.zeros(2,1,2,1,2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [90]:
x.size()

torch.Size([2, 1, 2, 1, 2])

In [91]:
torch.squeeze(x), torch.squeeze(x).size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [92]:
torch.squeeze(x, dim=1), torch.squeeze(x, dim=1).size() # the dim checks if at that position of the dim is a 1 or not and if it is then it removes that 1 dim

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))

**Unsqueeze** - add a 1 dimension to a tensor

In [93]:
x_squeezed = torch.squeeze(x)
x_squeezed.shape

torch.Size([2, 2, 2])

In [97]:
x_unsqueezed = torch.unsqueeze(x_squeezed, dim=1) # adds a 1 dim at that dim position
x_unsqueezed.shape

torch.Size([2, 1, 2, 2])

**Permute** - return a view of the tensor with dimensions swapped in a certain way

In [98]:
x = torch.randn(2, 3, 5)
x.size()

torch.Size([2, 3, 5])

In [102]:
x_permuted = torch.permute(x, dims=(2, 0, 1)) # takes in the index positions of the dimentions you want to swap around and in what way

x_permuted.size()

torch.Size([5, 2, 3])

In [103]:
x

tensor([[[-0.8185,  0.9297, -0.6051,  0.3683, -1.3801],
         [ 0.3148, -1.4347,  0.8238,  0.0131,  1.5738],
         [-0.7429, -0.1205,  1.3126,  1.3303,  0.9699]],

        [[ 0.4406,  0.4956, -0.7932, -0.1525,  0.5412],
         [-0.4951,  0.7667,  0.2211, -1.5523, -0.6291],
         [ 0.1108, -0.0849, -1.4399,  1.7431,  0.4661]]])

In [105]:
x[0,0,0] = 35

In [106]:
x_permuted[0,0,0]

tensor(35.)

In [101]:
rgb = torch.rand(size=(224, 224, 3)) # [h , w, c]

rgb_permuted = torch.permute(rgb, dims=(2, 0, 1))
rgb_permuted.size()

torch.Size([3, 224, 224])

### Indexing Tensors

In [132]:
x = torch.randint(11, (1, 3, 3))
x

tensor([[[ 7, 10,  6],
         [ 2,  9,  7],
         [ 3,  5,  5]]])

In [133]:
x[0]

tensor([[ 7, 10,  6],
        [ 2,  9,  7],
        [ 3,  5,  5]])

In [134]:
x[0][1]

tensor([2, 9, 7])

In [135]:
x[0][1][0]

tensor(2)

In [136]:
x[:, 0] # use ':' to target all values of a dimension

tensor([[ 7, 10,  6]])

In [137]:
x[:, :, 0] # first values of each row of each matrix

tensor([[7, 2, 3]])

In [138]:
x[:, 1, 1]

tensor([9])

In [139]:
x[:, 2, 2]

tensor([5])

In [140]:
x[:, :, 2]

tensor([[6, 7, 5]])

### Tensors and NumPy
* Converting data `torch.from_numpy(ndarray)`, `torch.Tensor.numpy()`

In [145]:
nd_array = np.arange(1, 10)
tensor = torch.from_numpy(nd_array).type(torch.float32) # the dtype might not be what you want since it doesn't convert it to the default dtype of a tensor
nd_array, tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [147]:
tensor = torch.ones(9)
nd_tensor = tensor.numpy()

tensor, nd_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

In [160]:
x = torch.rand(3, 4)
y = torch.rand(3, 4)

print(x)
print(y)
print(x == y)

tensor([[0.6965, 0.9143, 0.9351, 0.9412],
        [0.5995, 0.0652, 0.5460, 0.1872],
        [0.0340, 0.9442, 0.8802, 0.0012]])
tensor([[0.5936, 0.4158, 0.4177, 0.2711],
        [0.6923, 0.2038, 0.6833, 0.7529],
        [0.8579, 0.6870, 0.0051, 0.1757]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [165]:
# Setting the random seed in pytorch

RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED) # only works for one method block
x = torch.rand(3, 4)


torch.manual_seed(RANDOM_SEED)
y = torch.rand(3, 4)

print(x)
print(y)
print(x == y)

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Putting Tensor (and models) on and off a GPU

In [167]:
tensor = torch.tensor([1,2,3], device="mps") # mps for metal/mac
print(tensor, tensor.device)

tensor([1, 2, 3], device='mps:0') mps:0


In [168]:
tensor.numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [169]:
tensor.cpu().numpy()

array([1, 2, 3])