# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness)


In [1]:
import torch

print(f"PyTorch Version: {torch.__version__}")

# Check PyTorch has access to MPS (Metal Performance Shader, Apple's GPU architecture)
print(f"Is MPS (Metal Performance Shader) built? {torch.backends.mps.is_built()}")
print(f"Is MPS available? {torch.backends.mps.is_available()}")

# Set the device
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {device}")

PyTorch Version: 2.0.1
Is MPS (Metal Performance Shader) built? True
Is MPS available? True
Using device: mps


### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
rand_tensor = torch.rand(7,7)
rand_tensor

tensor([[0.3485, 0.8124, 0.5419, 0.7428, 0.1765, 0.3939, 0.6190],
        [0.1560, 0.5551, 0.3305, 0.3072, 0.8462, 0.5101, 0.7233],
        [0.5864, 0.0150, 0.8286, 0.6679, 0.3463, 0.5998, 0.5191],
        [0.6390, 0.9692, 0.8985, 0.0467, 0.6048, 0.3126, 0.0331],
        [0.9185, 0.0261, 0.2042, 0.0444, 0.7070, 0.9438, 0.5031],
        [0.5072, 0.6187, 0.9117, 0.6306, 0.4979, 0.5706, 0.7698],
        [0.7467, 0.7040, 0.3414, 0.7191, 0.2598, 0.6969, 0.5021]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
x = torch.rand(1, 7)
x = x.T
# Perform matrix multiplication 
torch.mm(rand_tensor, x)

tensor([[2.5129],
        [2.4786],
        [2.3101],
        [2.2417],
        [2.4235],
        [3.0584],
        [2.7705]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.rand(7,7)
y = torch.rand(1,7).T
# Matrix multiply tensors
torch.mm(x, y)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [12]:
# Set random seed on the GPU
torch.mps.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [40]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.has_mps

# Create two random tensors on GPU
x = torch.rand(size=(2,3), device="mps")
y = torch.rand(size = (2,3), device="mps")

x,y

(tensor([[0.4794, 0.7608, 0.8283],
         [0.8029, 0.6423, 0.0597]], device='mps:0'),
 tensor([[0.0223, 0.9878, 0.2711],
         [0.9123, 0.7672, 0.8879]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [27]:
# Perform matmul on tensor_A and tensor_B
torch.mm(x, y.T)

tensor([[0.9868, 1.7565],
        [0.6685, 1.2782]], device='mps:0')

### 8. Find the maximum and minimum values of the output of 7.

In [29]:
# Find max
tensor = torch.mm(x, y.T)
# Find min

tensor.min(), tensor.max()

(tensor(0.6685, device='mps:0'), tensor(1.7565, device='mps:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [32]:
# Find arg max


# Find arg min
tensor.argmin(), tensor.argmax()


(tensor(2, device='mps:0'), tensor(1, device='mps:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [34]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand_tensor = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
squeezed_tensor = torch.squeeze(rand_tensor)

# Print out tensors and their shapes
print((rand_tensor, rand_tensor.size()))
print((squeezed_tensor, squeezed_tensor.size()))

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10]))
(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10]))
